---
- name: Power off all VMs
  hosts: bootstrap_grp, masters_grp, infra_routers_grp
  become: no
  gather_facts: no

  vars_files:
    - vault.yml

  tasks:
    # - name: Include VMware variables
    #   include_vars: rhel_vmware.yml
    #   when: vcenter_hostname | default()

    # - name: Include RHV variables
    #   include_vars: rhel_rhv.yml
    #   when: rhv_hostname | default()

    # - include_role:
    #     name: rhv_provision
    #   when: rhv_hostname | default()

    - name: Authenticate to oVirt
      ovirt_auth:
        username: "{{ rhv_username }}"
        password: "{{ rhv_password }}"
        url: "https://{{ rhv_hostname }}/ovirt-engine/api"
        insecure: True
      delegate_to: localhost

    - name: Power off VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: stopped
        name: "{{ inventory_hostname }}"
      delegate_to: localhost

    # - name: Power off vm
    #   vmware_guest_powerstate:
    #     hostname: "{{ vcenter_hostname }}"
    #     username: "{{ vcenter_username }}"
    #     password: "{{ vcenter_password }}"
    #     validate_certs: "{{ vcenter_validate_cert }}"
    #     folder: "{{ vm_folder }}"
    #     name: "{{ inventory_name }}"
    #     state: shutdown-guest
    #     state_change_timeout: 200
    #   delegate_to: localhost

- name: LB check
  hosts: localhost 
  become: no
  gather_facts: no
    
  vars_files:
    - vault.yml

  vars:
    master_lb_ports:
      - 6443
      - 22623
    apps_lb_ports:
      - 80
      - 443

  tasks:  
    - name: "Authenticate to oVirt"
      ovirt_auth:
        username: "{{ rhv_username }}"
        password: "{{ rhv_password }}"
        url: "https://{{ rhv_hostname }}/ovirt-engine/api"
        insecure: True

    # Let's do masters first
    - set_fact:
        test_hosts: "{{ (groups['bootstrap_grp'] + groups['masters_grp'] + groups['infra_routers_grp']) | sort }}"
        #test_hosts: "{{ groups['masters'] | sort }}"
        #test_hosts: "{{groups['infra_routers'] | sort }}"
    
    - name: List of hosts to test
      debug:
        var: test_hosts

    - name: Test LB
      include_role:
        role: lb_check
      loop: "{{ test_hosts }}"
      loop_control:
        loop_var: outer_item
        label: "{{ outer_item }}"
  
    - template:
        src: templates/lb_check.txt.j2
        dest: /tmp/lb_check.txt
      vars:
        masters_lb_ip: "{{hostvars[groups['master_lb'][0]]['ansible_host']}}"
        apps_lb_ip: "{{hostvars[groups['apps_lb'][0]]['ansible_host']}}"
        

    