---
- name: OpenShift Setup
  hosts: bastion_grp
  connection: local
  become: no

  vars:
    rhcos_ignition_dest_path: /var/www/html/ignition

  vars_files:
    - vault.yml

  tasks:    
    - name: Create OCP installer files
      include_role:
        name: openshift_installer

- name: Destroy all OCP vms
  import_playbook: destroy.yml

- name: Provision OCP vms
  hosts: ocp
  become: yes
  gather_facts: no

  vars_files:
    - vault.yml
    - vars/rhel_vmware.yml
  
  tasks:
    - include_role:
        name: vmware_provision
      vars:
        vm_state: poweredon    
        cdrom_iso: 
          - type: iso
            iso_path: "[{{iso_datastore}}] {{iso_datastore_path}}/{{inventory_hostname}}.iso"
            controller_number: 0
            unit_number: 0
            state: present
        vm_customization: {}
        vm_template: 
        vm_guest_id: rhel8_64Guest

