---
- name: Validate OCP CIDR
  hosts: localhost
  become: no
  gather_facts: no

  tasks:
    - set_fact:
        host_network_cidr: "{{hostvars[groups['ocp'][0]].ansible_host}}/{{vm_netmask}}"
        cluster_size: "{{ (openshift_cluster_network_cidr | ipaddr('size'))}}"
        max_pod_ips: "{{ (2 | pow(32 - openshift_host_prefix))}}"

    - debug:
        msg: "{{item}}"
      loop:
        - "This is the host subnet: {{ host_network_cidr | ipaddr(0) }}"
        - "Total hosts available: {{host_network_cidr | ipaddr('size') - 2}}"
        - "This is the cluster subnet: {{openshift_cluster_network_cidr | ipaddr(0) }}"
        - "This is the host prefix: {{openshift_host_prefix}}"
        - "This is the service subnet: {{openshift_service_network_cidr | ipaddr(0) }}"
        - "Based on the host prefix, max hosts = {{ cluster_size | int / max_pod_ips | int}}. max pods per host = {{max_pod_ips | int - 2}}"
        - "Based on  service subnet, max service ips = {{ openshift_service_network_cidr | ipaddr('size') }}"

    - pause: 
        prompt: "Are you sure you want to continue (ctrl+c to abort. Any key to continue)?"
      
- name: OpenShift Setup
  hosts: localhost
  become: no
  gather_facts: no

  vars:
    rhcos_image_dest_path: /var/www/html/install/
    rhcos_ignition_dest_path: /var/www/html/ignition

  vars_files:
    - vault.yml

  tasks:
    - name: Ensure /var/www/html/install exists
      file:
        path: "{{rhcos_image_dest_path}}"
        state: directory  
        owner: root
        group: root
        mode: 0644    
      delegate_to: "{{ groups['mirror'][0] }}"

    - name: Copy RHCOS image to mirror server /var/www/html/install
      copy:
        src: "{{rhcos_image_path}}"
        dest: "{{rhcos_image_dest_path}}"
      delegate_to: "{{ groups['mirror'][0] }}"

    - name: Create boot iso
      include_role:
        name: custom_iso
      vars:
        rhcos_image_url: "http://{{ groups['mirror'][0] + '.' + dns_domain }}/install/{{rhcos_image_dest_path | basename}}"
        ignition_url: "http://{{ groups['mirror'][0] + '.' + dns_domain }}/ignition"

    - name: Create OCP installer files
      include_role:
        name: openshift_installer
      
# - name: Provision OpenShift VMs
#   hosts: localhost
#   become: no
#   gather_facts: no

#   vars_files:
#     - vault.yml
  
#   tasks:
#     - debug: msg: ""
