dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: rhsm-basic-subscription
    groups:
      - rhsm
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../shared/group_vars
  playbooks:
    create: ../openstack/create.yml
    destroy: ../openstack/destroy.yml
    prepare: ../shared/prepare.yml
  config_options:
    defaults:
      stdout_callback: yaml
scenario:
  name: basic_subscription
verifier:
  name: testinfra
  options:
    v: true
    junit-xml: junit.xml
  lint:
    name: flake8
