- name: converge
  hosts: all
  roles:
    - role: rhsm
  vars:
    rhsm_repositories:
      only:
        - rhel-7-server-rpms
        - rhel-7-server-optional-rpms
        - rhel-7-server-extras-rpms
