---
# tasks file for vmware_provision
- name: Construct disk var
  set_fact:
    disks: "{{ disks | default([]) + [{'size_gb': item.size, 'type': vm_disk_type, 'datastore': vm_datastore}] }}"
  loop: "{{ vm_disks }}"

- name: Create a virtual machine
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_cert }}"
    folder: "{{ vm_folder }}"
    name: "{{ inventory_hostname + '.' + dns_domain }}"
    state: "{{ vm_state }}"
    datacenter: "{{ vm_datacenter }}"
    cluster: "{{ vm_cluster }}"
    guest_id: "{{ vm_guest_id }}"
    template: "{{ vm_template }}"
    disk: "{{ disks }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_cpu }}"
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: True
      vm_hardware_version: "{{ vm_hardware_version }}" 
    networks:
      - name: "{{ vm_network_name }}"
        ip: "{{ ansible_host }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
        customization: "{{ vm_customization }}"
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy

- name: Wait for system to become reachable over SSH
  wait_for_connection:
    timeout: 300
