---
# tasks file for pip-repo
- name: Ensure pip path exists
  file:
    path: "/var/www/html/pip"
    state: directory
    mode: '0755'

- name: Copy pip mirror to destination
  synchronize:
    src: "{{ pip_path }}/"
    dest: /var/www/html/repos/pip
    recursive: yes

# restorecon /var/www/httpd
- name: restorecon /var/www/html/pip
  command: restorecon -vR /var/www/html/pip


