---
- name: "{{outer_item}} | Set fact for iso_file var"
  set_fact:
    iso_file: "{{iso_output_dir}}/{{outer_item}}.iso"
  
- name: "{{outer_item}} | Create iso directory"
  file:
    path: "{{iso_output_dir}}"
    state: directory

- name: "{{outer_item}} | Modify boot entry"
  template:
    src: isolinux.cfg.j2
    dest: "{{host_iso_build_path}}/isolinux/isolinux.cfg" 
  vars:
    vm_ip: "{{hostvars[outer_item].ansible_host}}"
    vm_name: "{{outer_item}}"
    ignition_file: "{{hostvars[outer_item].ignition_file}}"

# https://shanna-chan.blog/2019/07/26/openshift4-vsphere-static-ip/
- name: "{{outer_item}} | Create new RHCOS ISO "
  command: "mkisofs {{mkisofs_opts}}"
  args:
    chdir: "{{host_iso_build_path}}"
  vars:
    output_iso_path: "{{iso_file}}"
    name: "{{outer_item}}"      
  register: output

- name: Upload ISO to VMware datastore
  vsphere_copy:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: "{{ not vcenter_insecure_ssl }}"
    src: "{{iso_file}}"
    datacenter: "{{iso_datacenter}}"
    datastore: "{{iso_datastore}}"
    path: "{{iso_datastore_path}}/{{iso_file | basename }}"

