---
# vars file for custom ISO 
boot_option: "ip={{vm_ip}}::{{vm_gateway}}:{{vm_netmask}}:{{vm_name + '.' + dns_domain}}:{{vm_interface_name}}:none nameserver={{vm_dns[0]}} coreos.inst.install_dev={{vm_install_dev}} coreos.inst.image_url={{rhcos_image_url}} coreos.inst.ignition_url={{ignition_url}}/{{ignition_file}}"
mkisofs_opts: "-U -A {{ name }} -V {{ name }} -volset {{ name }} -J -joliet-long -r -v -T -x ./lost+found -o {{output_iso_path}} -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e images/efiboot.img -no-emul-boot ."

